# Dockerfile.production

FROM registry.semaphoreci.com/golang:1.18 as builder

ENV APP_HOME /go/src/go-web-docker

WORKDIR "$APP_HOME"
COPY src/ .

RUN go mod download
RUN go mod verify
RUN go build -o go-web-docker

FROM registry.semaphoreci.com/golang:1.18

ENV APP_HOME /go/src/go-web-docker
RUN mkdir -p "$APP_HOME"
WORKDIR "$APP_HOME"

COPY src/conf/ conf/
COPY src/views/ views/
COPY --from=builder "$APP_HOME"/go-web-docker $APP_HOME

EXPOSE 8010
CMD ["./go-web-docker"]